### ISSUE TITLE
Ingredients count/size/measurement are not displayed in the ui

### ISSUE THREAD

**Issue by mmlb** [open-eats/OpenEats#33] opened 2018-04-15 17:02 UTC
Just fired up openeats following the -prod instructions. I added the bare minimum of a recipe to check this project out. I've entered the ingredients following the tooltip help:

```
8 bone-in, skin-on chicken thighs
5 chickens
1.5 cups of water
```
but none of the count/size numbers are being rendered in the webpage:
![screenshot-2018-4-15 openeats](https://user-images.githubusercontent.com/708570/38780955-40f65d26-40ac-11e8-9c21-826605bd756f.png)
 The preview link correctly displays the numbers:
![screenshot-2018-4-15 openeats 1](https://user-images.githubusercontent.com/708570/38780976-85eee8d0-40ac-11e8-96cb-60a6b6092a45.png)

The api response looks like:
```json
{
  "id": 1,
  "photo": null,
  "photo_thumbnail": null,
  "ingredient_groups": [
    {
      "id": 6,
      "title": "",
      "ingredients": [
        {
          "id": 11,
          "numerator": 1,
          "denominator": 1,
          "measurement": "bone-in,",
          "title": "skin-on chicken thighs"
        },
        {
          "id": 12,
          "numerator": 1,
          "denominator": 1,
          "measurement": null,
          "title": "chickens"
        },
        {
          "id": 13,
          "numerator": 1,
          "denominator": 1,
          "measurement": "cups",
          "title": "of water"
        }
      ]
    }
  ],
  "tags": [],
  "subrecipes": [],
  "pub_date": "2018-04-15",
  "update_date": "2018-04-15",
  "username": "manny",
  "title": "Lemon Butter Chicken",
  "slug": "lemon-butter-chicken",
  "info": "Easy crips-tender chicken with the creamiest lemon butter sauce ever.",
  "directions": "Do it",
  "source": "",
  "prep_time": 10,
  "cook_time": 40,
  "servings": 8,
  "rating": 0,
  "public": true,
  "author": 1,
  "cuisine": 3,
  "course": 2
}
```

**Comment by RyanNoelk** [comment] 2018-04-15 17:07
Strange! Will take a look tonight and try and have a fix soon. I think I know what the issue is.

**Comment by mmlb** [comment] 2018-04-15 17:11
ok nice, btw the test/sample recipes are missing numbers in the original (I assume) tasty chilli recipe.

**Comment by RyanNoelk** [comment] 2018-04-15 23:40
Looks like there was just an issue with the automated build. So your instance wasn't using the most recent code, causing some issues. This should be fixed now.

See: https://hub.docker.com/r/openeats/openeats-web/builds/

**Comment by mmlb** [comment] 2018-04-17 11:54
ok nice, I'll give it another go

**Comment by RyanNoelk** [comment] 2018-04-18 16:57
Cool. Please close this if that solves things. I was able to reproduce and this fixed it.

**Closed as completed** 2018-04-29 11:52 UTC
